services:
  db:
    image: postgres:latest
    shm_size: 1g
    command: -c config_file=/etc/postgresql.conf
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres 
      POSTGRES_DB: postgres 
    ports:
      - 15432:5432
    build: ./postgres
    volumes:
      - ./db-data:/var/lib/postgresql/data/
      - ./db-init-scripts:/docker-entrypoint-initdb.d
      - ./db-config/postgresql.conf:/etc/postgresql.conf
      - ./db-config/pg_hba.conf:/etc/postgresql/pg_hba.conf

networks: 
  postgres-network:
    driver: bridge
